### ISSUE TITLE
Sample issue

### ISSUE THREAD

**Issue by Zyapagetti** [Zyapagetti/issue-practice#1]
## Description

This is a sample of an issue
한 줄 설명해주세요
수식 표현이 필요하다면 $y=ax+b$

## Tasks

- [ ] Set issue template
- [ ] Set Labels, Milestones
- [ ] Projects Scrum board
- [ ] Close Issue

## References

- [Google](https://www.google.com/)
